<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<jsp:include page="intestazione.jsp" />

<main id="mainBody">

    <h1>ATTIVITA'</h1>

    <div>
        DESCRIZIONE ATTIVITA/DESCRIZIONE ATTIVITA/DESCRIZIONE ATTIVITA/DESCRIZIONE ATTIVITA//DESCRIZIONE ATTIVITA/
        DESCRIZIONE ATTIVITA/DESCRIZIONE ATTIVITA/DESCRIZIONE ATTIVITA/DESCRIZIONE ATTIVITA//DESCRIZIONE ATTIVITA/
        DESCRIZIONE ATTIVITA/DESCRIZIONE ATTIVITA/DESCRIZIONE ATTIVITA/DESCRIZIONE ATTIVITA//DESCRIZIONE ATTIVITA/
        DESCRIZIONE ATTIVITA/DESCRIZIONE ATTIVITA/DESCRIZIONE ATTIVITA/DESCRIZIONE ATTIVITA//DESCRIZIONE ATTIVITA/
        DESCRIZIONE ATTIVITA/DESCRIZIONE ATTIVITA/DESCRIZIONE ATTIVITA/DESCRIZIONE ATTIVITA//DESCRIZIONE ATTIVITA/
    </div>

    <a href="#">attivita1</a>
    <a href="#">attivita2</a>
    <a href="#">attivita3</a>

</main>

<jsp:include page="footer.jsp"/>